Category.create(name:'感謝')
Category.create(name:'教訓')
Category.create(name:'感情')
Post.create(fact:'上司への説明にイライラ', notice:'正直こういう仕事はもう嫌だ',category_id:'1',user_id: '2')
Post.create(fact:'お米を久々に食べる', notice:'やっぱりご飯食べないとエネルギーでないや',category_id:'1',user_id: '3')
Post.create(fact:'仲間が優しい言葉をかけてくれた', notice:'たとえ嘘でもありがたい',category_id:'1',user_id: '1')
